### PR TITLE
Updated package.json module exports

### PR DESCRIPTION
**Pull request by deerware**
This certainly needs more testing, I only tested it with nativeJS import, but it seems to fix issues #9 and #34 with webpack.

### CODE REVIEW

**Comment by zaynbuksh** [comment]
@justin-schroeder I can confirm that this fixes #57 on my machine. This looks similar to the workaround that @deerware used for #34 and may help for others such as #36.

**Comment by zaynbuksh** [comment]
Hi @justin-schroeder - could you release this please?

**Comment by justin-schroeder** [comment]
Yes — probably @zaynbuksh. I've never seen an array syntax in an export map before and I cannot find reference to it — is anyone able to dig that up. I'm also curious if just specifying "default" for each would be sufficient:

```js
{
"exports": {
   "./vue": {
      "import": "./vue/index.mjs",
      "types": "./vue/index.d.ts",
      "default": "./vue/index.mjs"
    },
    "./react": {
      "import": "./react/index.mjs",
      "types": "./react/index.d.ts",
      "default": "./react/index.mjs"
    },
    "./angular": {
      "import": "./angular/index.mjs",
      "types": "./angular/index.d.ts"
      "default": "./angular/index.mjs"
    },
    ".": {
      "import": "./index.mjs"
      "default": "./index.mjs"
    }
}
```

**Comment by deerware** [comment]
@justin-schroeder As far as i know "default" should be sufficient. It should be the same as specifying the standalone value in the array.

**Comment by justin-schroeder** [comment]
@deerware where did you originally find that array syntax? I cant find it in the node docs, and im not sure there's a specific spec out there — at least not one I can find.

**Comment by deerware** [comment]
@justin-schroeder I couldn't find it either. I was just comparing your package.json to some random module that was working correctly for me and copied it from there. No documented research there unfortunately

**Comment by justin-schroeder** [comment]
@deerware ok thanks. Yeah the landscape of bundlers and module resolutions is regrettably disparate. I think it might be safer to go with the `default` option since I can at lest find documented proof of that.

**Pull request merged**
